allowBuilds:
  esbuild: true
  msgpackr-extract: true
overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vitest: "npm:@voidzero-dev/vite-plus-test@latest"
minimumReleaseAgeExclude:
  - "@instantdb/admin@1.0.42"
  - "@instantdb/core@1.0.42"
  - "@instantdb/react-common@1.0.42"
  - "@instantdb/react@1.0.42"
  - "@instantdb/version@1.0.42"
  - "@instantdb/webhooks@1.0.42"
  - "@tanstack/react-router@1.170.10"
  - "@tanstack/react-start-client@1.168.7"
  - "@tanstack/react-start-rsc@0.1.16"
  - "@tanstack/react-start-server@1.167.12"
  - "@tanstack/react-start@1.168.17"
  - "@tanstack/router-core@1.171.8"
  - "@tanstack/router-generator@1.167.12"
  - "@tanstack/router-plugin@1.168.13"
  - "@tanstack/start-client-core@1.170.6"
  - "@tanstack/start-plugin-core@1.171.9"
  - "@tanstack/start-server-core@1.169.7"
  - "@tanstack/start-storage-context@1.167.10"
  - oxlint-plugin-react-doctor@0.2.12
  - react-doctor@0.2.12
